"""add workspaces table

Revision ID: 6e1e54692032
Revises: 
Create Date: 2020-10-24 12:37:22.095657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1e54692032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_type', sa.String(length=255), nullable=True),
    sa.Column('workspace_name', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('generated_channel_id', sa.String(length=255), nullable=True),
    sa.Column('generated_channel_name', sa.String(length=255), nullable=True),
    sa.Column('auth_token', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    # ### end Alembic commands ###
