"""add additional workspace fields

Revision ID: b57ce6d1c9ca
Revises: 6e1e54692032
Create Date: 2020-10-24 12:49:16.334637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57ce6d1c9ca'
down_revision = '6e1e54692032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('permissions', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('project_channel_id', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('project_channel_name', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('project_channel_recent_messages', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('project_id', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('refresh_token', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('scope', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.add_column('workspaces', sa.Column('token_type', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'username')
    op.drop_column('workspaces', 'token_type')
    op.drop_column('workspaces', 'token_expiration')
    op.drop_column('workspaces', 'scope')
    op.drop_column('workspaces', 'refresh_token')
    op.drop_column('workspaces', 'project_id')
    op.drop_column('workspaces', 'project_channel_recent_messages')
    op.drop_column('workspaces', 'project_channel_name')
    op.drop_column('workspaces', 'project_channel_id')
    op.drop_column('workspaces', 'permissions')
    # ### end Alembic commands ###
